### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by viktorprogger** [viktorprogger/telegram-rss-bot#10]
- [ ] Move readers and senders to the new `src` directory
- [ ] Add a Sender to send messages to `stdout`
- [ ] Create a console command to read RSS and send messages
- [ ] Create repos and DTOs, configure the `yii-cycle` package
- [ ] Add Sentry integration
- [ ] ***Release the new version to the `master` branch***
- [ ] Add RoadRunner binary
- [ ] Add entry point (.php file) for the RoadRunner to deal with http requests
- [ ] Review and fix RR config
- [ ] Add [Temporal server](https://github.com/temporalio/docker-compose/blob/main/docker-compose.yml) to the `docker-compose.yml`. Use the default DB integration, Cassandra.
- [ ] Add [Temporal SDK](https://github.com/temporalio/sdk-php)
- [ ] Add Temporal to the RR config
- [ ] Rewrite console commands to use Temporal
- [ ] ***Release the new version to the `master` branch***
- [ ] Add Github notification bot (#9)
- [ ] ***Release the new version to the `master` branch***

**Comment by viktorprogger** [comment]
Next steps:
- An integration with email inbox to send notifications to Telegram or JB Space
- Endpoint to receive webhooks from Sentry
- Endpoint to receive webhooks from NewRelic
- Integrate JB Space issues with GitHub issues to provide the Yiisoft an ability to comfortably manage Yii3 project
